
# Custom Prometheus Alert Rules for DaorsAgro

groups:
  - name: daorsagro_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected in {{ $labels.service }}"
          description: "Error rate is above 5% for last 5 minutes"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency in {{ $labels.service }}"
          description: "95th percentile latency is above 500ms"

      - alert: HighDBConnections
        expr: postgresql_connections_active > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High database connections"
          description: "Active connections above 80%"

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity