global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'financial-service'
    static_configs:
      - targets: ['financial-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'subsidy-service'
    static_configs:
      - targets: ['subsidy-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'insurance-service'
    static_configs:
      - targets: ['insurance-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:3005']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'document-service'
    static_configs:
      - targets: ['document-service:3006']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3007']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'iot-service'
    static_configs:
      - targets: ['iot-service:3008']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 60s

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 60s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 60s