# Prometheus Alerting Rules for DaorsAgro
groups:
  - name: daorsagro.infrastructure
    rules:
      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for more than 5 minutes on {{ $labels.instance }}"

      # Disk space usage
      - alert: DiskSpaceUsage
        expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"}) > 85
        for: 5m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is above 85% for more than 5 minutes on {{ $labels.instance }}"

  - name: daorsagro.databases
    rules:
      # PostgreSQL connection issues
      - alert: PostgreSQLDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
          service: postgresql
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database is not responding on {{ $labels.instance }}"

      # PostgreSQL high connection usage
      - alert: PostgreSQLHighConnections
        expr: (pg_stat_database_numbackends / pg_settings_max_connections) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "PostgreSQL high connection usage"
          description: "PostgreSQL connection usage is above 80% on {{ $labels.instance }}"

      # MongoDB connection issues
      - alert: MongoDBDown
        expr: mongodb_up == 0
        for: 1m
        labels:
          severity: critical
          service: mongodb
        annotations:
          summary: "MongoDB is down"
          description: "MongoDB database is not responding on {{ $labels.instance }}"

      # Redis connection issues
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis is down"
          description: "Redis cache is not responding on {{ $labels.instance }}"

      # Redis high memory usage
      - alert: RedisHighMemoryUsage
        expr: (redis_memory_used_bytes / redis_memory_max_bytes) * 100 > 90
        for: 5m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis high memory usage"
          description: "Redis memory usage is above 90% on {{ $labels.instance }}"

  - name: daorsagro.applications
    rules:
      # API Gateway health
      - alert: APIGatewayDown
        expr: up{job="api-gateway"} == 0
        for: 1m
        labels:
          severity: critical
          service: api-gateway
        annotations:
          summary: "API Gateway is down"
          description: "API Gateway is not responding on {{ $labels.instance }}"

      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: "{{ $labels.service }}"
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 2 seconds for {{ $labels.service }}"

      # High error rate
      - alert: HighErrorRate
        expr: (rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])) * 100 > 5
        for: 5m
        labels:
          severity: warning
          service: "{{ $labels.service }}"
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for {{ $labels.service }}"

      # Service down
      - alert: ServiceDown
        expr: up{job=~".*-service"} == 0
        for: 1m
        labels:
          severity: critical
          service: "{{ $labels.job }}"
        annotations:
          summary: "Service is down"
          description: "{{ $labels.job }} is not responding on {{ $labels.instance }}"

  - name: daorsagro.kafka
    rules:
      # Kafka broker down
      - alert: KafkaBrokerDown
        expr: kafka_brokers == 0
        for: 1m
        labels:
          severity: critical
          service: kafka
        annotations:
          summary: "Kafka broker is down"
          description: "No Kafka brokers are available"

      # High consumer lag
      - alert: KafkaConsumerLag
        expr: kafka_consumer_lag_sum > 1000
        for: 5m
        labels:
          severity: warning
          service: kafka
        annotations:
          summary: "High Kafka consumer lag"
          description: "Consumer lag is above 1000 messages for topic {{ $labels.topic }}"

  - name: daorsagro.elasticsearch
    rules:
      # Elasticsearch cluster health
      - alert: ElasticsearchClusterRed
        expr: elasticsearch_cluster_health_status{color="red"} == 1
        for: 1m
        labels:
          severity: critical
          service: elasticsearch
        annotations:
          summary: "Elasticsearch cluster is red"
          description: "Elasticsearch cluster health is red"

      # Elasticsearch cluster yellow
      - alert: ElasticsearchClusterYellow
        expr: elasticsearch_cluster_health_status{color="yellow"} == 1
        for: 5m
        labels:
          severity: warning
          service: elasticsearch
        annotations:
          summary: "Elasticsearch cluster is yellow"
          description: "Elasticsearch cluster health is yellow for more than 5 minutes"

  - name: daorsagro.business
    rules:
      # Low user activity
      - alert: LowUserActivity
        expr: rate(user_login_total[1h]) < 10
        for: 30m
        labels:
          severity: warning
          service: business
        annotations:
          summary: "Low user activity detected"
          description: "User login rate is below 10 per hour for the last 30 minutes"

      # Failed payment processing
      - alert: HighPaymentFailures
        expr: (rate(payment_failures_total[5m]) / rate(payment_attempts_total[5m])) * 100 > 10
        for: 5m
        labels:
          severity: critical
          service: financial
        annotations:
          summary: "High payment failure rate"
          description: "Payment failure rate is above 10% for the last 5 minutes"

      # Document processing failures
      - alert: DocumentProcessingFailures
        expr: rate(document_processing_failures_total[5m]) > 5
        for: 5m
        labels:
          severity: warning
          service: document
        annotations:
          summary: "High document processing failures"
          description: "Document processing failure rate is above 5 per minute"

      # IoT device connectivity issues
      - alert: IoTDeviceConnectivityIssues
        expr: (iot_devices_connected / iot_devices_total) * 100 < 80
        for: 10m
        labels:
          severity: warning
          service: iot
        annotations:
          summary: "IoT device connectivity issues"
          description: "Less than 80% of IoT devices are connected"

  - name: daorsagro.security
    rules:
      # Too many failed login attempts
      - alert: TooManyFailedLogins
        expr: rate(failed_login_attempts_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "Too many failed login attempts"
          description: "Failed login attempts rate is above 10 per minute"

      # Suspicious API activity
      - alert: SuspiciousAPIActivity
        expr: rate(http_requests_total{status="401"}[5m]) > 20
        for: 5m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "Suspicious API activity detected"
          description: "High rate of 401 responses detected: {{ $value }} per minute"

      # SSL certificate expiration
      - alert: SSLCertificateExpiration
        expr: (ssl_certificate_expiry_seconds - time()) / 86400 < 30
        for: 1h
        labels:
          severity: warning
          service: security
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in {{ $value }} days"